apiVersion: v1
kind: Service
metadata:
  name: todo-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: todo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-deployment
  labels:
    app: todo-db
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "todo-db"
    tags.datadoghq.com/version: "12"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
        sidecar.istio.io/inject: "true"
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "todo-db"
        tags.datadoghq.com/version: "12"
      annotations:
        admission.datadoghq.com/java-lib.version: "latest"
    spec:
      containers:
        - name: db
          image: postgres:11.6-alpine
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/postgres_password
          volumeMounts:
            - name: secret
              mountPath: '/secrets'
      volumes:
        - name: secret
          secret:
            secretName: todo-db-secret-test
            defaultMode: 0400
            items:
              - key: POSTGRES_PASSWORD
                path: postgres_password
