apiVersion: v1
kind: Service
metadata:
  name: todo-web-service
spec:
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: todo-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web-deployment
  labels:
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: alpine
    tags.datadoghq.com/version: v1
spec:
  selector:
    matchLabels:
      app: todo-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-web
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: alpine
        tags.datadoghq.com/version: v1
    spec:
      containers:
        - name: web
          image: hancheo/todo-db-fix
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Test
            - name: DD_LOGS_INJECTION
              value: 'true'
          volumeMounts:
            - name: config
              mountPath: '/app/config'
              readOnly: true
            - name: secret
              mountPath: '/app/secrets'
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: todo-web-config-test
            items:
              - key: config.json
                path: config.json
        - name: secret
          secret:
            secretName: todo-web-secret-test
            defaultMode: 0400
            items:
              - key: secrets.json
                path: secrets.json
