apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: todo-web
spec:
  hosts:
    - '*'
  gateways:
    - todo-web-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: todo-web-service
            port:
              number: 8081
