# https://artifacthub.io/packages/helm/datadog/datadog
datadog:
  site: us5.datadoghq.com
  apiKey: f6701d7cb9da8f4e536ae207a3e2f552
  appKey: fc8f362168ca67cef945955fdf20b8585c555e15

  ## Set to true to enable the your cluster name
  clusterName: sandbox-eks
  collectEvents: false
  
  # "Set up the Istio integration"
  clusterChecks:
    enabled: false

  # Set up Istio log collection
  logs:
    enabled: true
    containerCollectAll: true
    autoMultiLineDetection: true

  dogstatsd:
    useSocketVolume: false
    useHostPort: true
  useHostPID: false




  apm:
    portEnabled: true
    port: 8126
    instrumentation:
      enabled: false
  processAgent:
    processCollection: true
  networkMonitoring:
    enabled: true

clusterAgent:
  enabled: true
  replicas: 1
  createPodDisruptionBudget: true
  # true 일경우 pod이 생성시 timeout error
  admissionController:
    enabled: false
    mutateUnlabelled: true
  podAnnotations:
    sidecar.istio.io/inject: "false"

agents:
  enabled: true
  replicas: 1
  tolerations:
    - operator: Exists
  podAnnotations:
    sidecar.istio.io/inject: "false"
