# https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
  tag: '1.22.3'
  meshConfig:
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing: # Enable Datadog Tracing
        # datadog:
        #   address: "$(HOST_IP):8126"
        # sampling: 100.0
      proxyMetadata:
        # https://github.com/istio/istio/issues/51430 istio brake datadog tracing
        DD_REMOTE_CONFIGURATION_ENABLED: "true"
      gatewayTopology:
        forwardClientCertDetails: ALWAYS_FORWARD_ONLY
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  values:
    global:
      istioNamespace: istio-system
  components:
    base:
      enabled: true
    cni:
      # Installation in kube-system is recommended to ensure the system-node-critical priorityClassName can be used. 
      # You can install in other namespace only on K8S clusters that allow 'system-node-critical' outside of kube-system.
      namespace: kube-system
      enabled: false
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 512Mi
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            externalTrafficPolicy: Local
          hpaSpec:
            minReplicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 1024Mi
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    pilot:
      enabled: true
      k8s:
        podAnnotations:
          ad.datadoghq.com/discovery.check_names: '["istio"]'
          ad.datadoghq.com/discovery.init_configs: '[{}]'
          # https://istio.io/latest/docs/ops/deployment/application-requirements/
          ad.datadoghq.com/discovery.instances: |
            [
              {
                "istiod_endpoint": "http://%%host%%:15014/metrics",
                "use_openmetrics": "true"
              }
            ]
        hpaSpec:
          minReplicas: 2
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1024Mi

