# https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
  tag: '1.22.3'
  meshConfig:
    enableTracing: true
    defaultConfig:
      # https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#example-using-x-forwarded-for-capability-with-httpbin
      gatewayTopology:
        numTrustedProxies: 1
      holdApplicationUntilProxyStarts: true
      tracing: # Enable Datadog Tracing
        # datadog:
        #   address: "$(HOST_IP):8126"
        # sampling: 100.0
      proxyMetadata:
        # https://github.com/istio/istio/issues/51430 istio brake datadog tracing
        DD_REMOTE_CONFIGURATION_ENABLED: "true"
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  values:
    global:
      istioNamespace: istio-system
    cni:
      excludeNamespaces:
        - istio-system
  components:
    cni:
      # Installation in kube-system is recommended to ensure the system-node-critical priorityClassName can be used. 
      # You can install in other namespace only on K8S clusters that allow 'system-node-critical' outside of kube-system.
      namespace: kube-system
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 512Mi
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 1024Mi
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*" 
            service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
            alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
            alb.ingress.kubernetes.io/healthcheck-port: '32197'
    pilot:
      enabled: true
      k8s:
        podAnnotations:
          ad.datadoghq.com/discovery.check_names: '["istio"]'
          ad.datadoghq.com/discovery.init_configs: '[{}]'
          # https://istio.io/latest/docs/ops/deployment/application-requirements/
          ad.datadoghq.com/discovery.instances: |
            [
              {
                "istiod_endpoint": "http://%%host%%:15014/metrics",
                "use_openmetrics": "true"
              }
            ]
        hpaSpec:
          minReplicas: 2
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1024Mi

